name: OWASP Dependency Scan

# Instructions for when the scan should be conducted
on:
  pull_request:
  push:
    branches:
      - master

# Actions that will be conducted when code is pushed
# currently ony one job is described containg all
# needed steps to complete the scan
jobs:
  sca-scan:
    # Filesystem used for the job
    runs-on: ubuntu-latest

    # Get the repository code
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Get the engine for the project
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Download the packages defined in package.json 
    - name: Install dependencies
      run: npm install

    # Using marketplace's action to run OWASP DC
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'vulnerable-nodejs-project'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired

    # Upload the report to GitHub's artifacts
    - name: Upload Dependency Check Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: ./reports/dependency-check-report.html
